add_newline = true

[character]
style_success = "bold fg:79"
style_failure = "bold fg:170"

[package]
disabled = true

[battery]
disabled = true

[directory]
truncate_to_repo = false
style = "bold fg:104"

[git_branch]
style = "fg:103"

[git_state]
style = "fg:104"

[git_status]
style = "fg:104"

[nodejs]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[python]
disabled = true
