add_newline = true

[character]
style_success = "bold fg:37"
style_failure = "bold fg:204"

[battery]
disabled = true

[directory]
truncate_to_repo = false
style = "bold fg:189"

[package]
disabled = true

[git_branch]
style = "bold fg:242"

[git_state]
style = "fg:189"

[git_status]
style = "fg:189"

[nodejs]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true
